name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - name: Manage cache
              uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
              with:
                  path: |
                      ~/.npm
                      ~/.yarn
                      ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-lint-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            - name: Use Node.js v16
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
              with:
                  node-version: 16
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Run next lint
              run: yarn lint

    Building:
        name: Compile source code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - name: Manage cache
              uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
              with:
                  path: |
                      ~/.npm
                      ~/.yarn
                      ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            - name: Use Node.js v16
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
              with:
                  node-version: 16
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Build Code
              run: yarn build
